# Generated by Django 3.2.5 on 2021-07-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_auto_20210720_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
